[package]
name = "observation"
version = "0.1.0"
edition = "2024"

[dependencies]
# Yellowstone gRPC client
yellowstone-grpc-client = "13.1.0"
yellowstone-grpc-proto = "12.4.0"

# Async runtime
tokio = { version = "1", features = ["full"] }

# gRPC transport
tonic = "0.14.6"

# Env vars
dotenvy = "0.15"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"